openapi: 3.0.3
info:
  title: TaskManager
  contact:
    email: 101461@aluno.uricer.edu.br
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: tasks
paths:
  /tasks:
    get:
      tags:
        - tasks
      summary: Finds all the tasks
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      tags:
        - tasks
      summary: Creates a new task
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
  /tasks/{id}:
    get:
      tags:
        - tasks
      summary: Finds a specific task
      parameters:
        - name: id
          in: path
          description: ID of Task to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '501':
          description: unsuccessful operation
    put:
      tags:
        - tasks
      summary: Updates an existing task
      parameters:
        - name: id
          in: path
          description: ID of Task to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    delete:
      tags:
        - tasks
      summary: Deletes a task
      parameters:
        - name: id
          in: path
          description: ID of Task to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Successful operation
  /tasks/{id}/finish:
    patch:
      tags:
        - tasks
      summary: Marks a task as done
      parameters:
        - name: id
          in: path
          description: ID of Task to mark as done
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Successful operation
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        description:
          type: string
          example: task description
        creationDate:
          type: string
          format: date
          example: 2024-05-21
        limitDate:
          type: string
          format: date
          example: 2024-05-21
        done:
          type: boolean
          example: false